# Sprint 4 : Architectures DL avancees (Google Colab)

Notebook de **configuration Colab** pour ResidualMLP, 1D-CNN et grid search. Les resultats finaux sont dans `05_dl_colab_tune.ipynb` (execute) et `reports/sprint_04_dl_comparison.csv`.

# Sprint 4 : Deep Learning : Architectures avancées

**AquaSense AI - EHTP MIG S4**

Objectifs :
- Residual MLP (skip connections)
- 1D-CNN sur features tabulaires
- Tableau comparatif MLP vs Residual vs CNN

> Alternative headless : `python -m src.train_dl` ou `python -m src.train_dl tune`

In [1]:
import sys
from pathlib import Path

import pandas as pd

PROJECT_ROOT = Path("..").resolve()
REPORTS_DIR = PROJECT_ROOT / "reports"

dl_csv = REPORTS_DIR / "sprint_04_dl_comparison.csv"
if not dl_csv.exists():
    raise FileNotFoundError(
        f"{dl_csv} absent : executer 05_dl_colab_tune.ipynb sur Colab"
    )
df_dl = pd.read_csv(dl_csv).sort_values("f1_macro", ascending=False)
print("Resultats DL archives (Colab) :")
df_dl

Resultats DL archives (Colab) :

,architecture,f1_macro,f1_needs_repair,recall_needs_repair,accuracy,deployable
0,mlp_l2_0.001,0.5410,0.3113,0.6025,0.6099,yes
1,mlp_baseline,0.5297,0.2992,0.5666,0.6038,yes
2,residual_mlp,0.5276,0.2743,0.3024,0.6341,yes
3,mlp_l2_0.0,0.5272,0.2973,0.5747,0.5984,yes
4,cnn1d,0.4113,0.1726,0.2260,0.5067,yes
5,mlp_tuned_grid,0.3817,0.2065,0.9305,0.3803,no

## Grid search + export TFLite (optionnel : long sur CPU)

In [2]:
import sys
from pathlib import Path

import pandas as pd

PROJECT_ROOT = Path("..").resolve()
REPORTS_DIR = PROJECT_ROOT / "reports"

dl_csv = REPORTS_DIR / "sprint_04_dl_comparison.csv"
if not dl_csv.exists():
    raise FileNotFoundError(
        f"{dl_csv} absent : executer 05_dl_colab_tune.ipynb sur Colab"
    )
df_dl = pd.read_csv(dl_csv).sort_values("f1_macro", ascending=False)
print("Resultats DL archives (Colab) :")
df_dl

Resultats DL archives (Colab) :

,architecture,f1_macro,f1_needs_repair,recall_needs_repair,accuracy,deployable
0,mlp_l2_0.001,0.5410,0.3113,0.6025,0.6099,yes
1,mlp_baseline,0.5297,0.2992,0.5666,0.6038,yes
2,residual_mlp,0.5276,0.2743,0.3024,0.6341,yes
3,mlp_l2_0.0,0.5272,0.2973,0.5747,0.5984,yes
4,cnn1d,0.4113,0.1726,0.2260,0.5067,yes
5,mlp_tuned_grid,0.3817,0.2065,0.9305,0.3803,no